apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- configmap.yml
labels:
- includeSelectors: true
  pairs:
    app: myapp
    managed-by: kustomize
